# Generated by Django 5.2.15 on 2026-06-07 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ubicacion',
            fields=[
                ('id_ubi', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
